### ISSUE TITLE
Dragging an item from one compendium with folders to another causes window locations to reset

### ISSUE THREAD

**Issue by nschoenwald** [Mushie1/subfolder-indent#6]
This is very annoying, as the windows are put right over each other every time you drag an item from one compendium to another.

**Comment by Mushie1** [comment]
Hi, I just tried to replicate this and it worked fine for me.
I tested in PF2e and DnD5e (3.3.1) with Foundry v12.331.

Can you please confirm which Foundry version you are using and what system (and system version).
What hosting are you using (local / forge / molten / oracle etc)

Also are you able to try it in a world with no other modules (there could be a conflict with one of them)
![image](https://github.com/user-attachments/assets/c1ba9522-2a3c-46a5-9e87-cfc2105ee192)

**Comment by nschoenwald** [comment]
Hi, I'm very sorry, appearantly this only occurs when Popout Resizer is also enabled. So likely not this module's fault.

**Comment by Mushie1** [comment]
No problem at all.  Glad you worked it out. :)
